name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_TOKEN: $ {{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKERHUB_TOKEN
      - name: Set up Docker Buildx & build
        run: |
          docker buildx create --driver cloud droyaltytestorg/default
          docker buildx build --builder cloud-droyaltytestorg-default -t droyaltestorg/testing:latest .
      - name: Push
        run: |
          docker push droyaltestorg/testing:latest

